name: Build and Release

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build-desktop:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            script: dist:linux
          - os: windows-latest
            platform: win
            arch: x64
            script: dist:win
          - os: macos-latest
            platform: mac
            arch: arm64
            script: dist:mac-arm64
          - os: macos-15-large
            platform: mac
            arch: x64
            script: dist:mac-x64
    env:
      GITEA_TOKEN: ${{ secrets.GITEA_TOKEN || secrets.TOKEN }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Desktop
        run: pnpm run ${{ matrix.script }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            dist/*.dmg
            dist/*.AppImage
            dist/*.exe

  release:
    needs: [build-desktop]
    runs-on: ubuntu-latest
    if: startsWith(gitea.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          merge-multiple: true

      - name: List Release Assets
        run: |
          echo "Release assets:"
          ls -la release-assets/

      - name: Generate Checksums
        run: |
          cd release-assets
          sha256sum * > SHA256SUMS || true
          cat SHA256SUMS

      - name: Create Release
        uses: http://192.168.199.239:8418/actions/release-action@main
        with:
          tag_name: ${{ gitea.ref_name }}
          name: ${{ gitea.ref_name }}
          draft: false
          files: release-assets/*
          fail_on_unmatched_files: false
